version: '3.2'
services:
  relay:
    container_name: pratmat-relay
    image: webhookrelay/webhookrelayd-aarch64:1.26.5
    network_mode: host # required if you want to access other services running on localhost (otherwise localhost would be inside this container)
    restart: unless-stopped
    environment:
      # Authentication
      - RELAY_KEY=${RELAY_KEY}
      - RELAY_SECRET=${RELAY_SECRET}
      # buckets list to subscribe
      - BUCKETS=${BUCKETS}

  # This is actually a pretty awesome container, but it's difficult to run scripts outside of the container.
  # Therefore this is run from the host instead.
  # webhook:
  #   container_name: pratmat-webhook
  #   image: thecatlady/webhook:2.8.0
  #   restart: unless-stopped
  #   command: -verbose -hooks=hooks.json -hotreload
  #   environment:
  #     - NO=Europe/Oslo #optional
  #   volumes:
  #     - /home/ubuntu/repos/matprat-website/production/webhooks:/config:ro
  #   ports:
  #     - 9000:9000
