#!/bin/bash
set -e

# Matprat Website Production Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/mariugul/matprat-website/main/production/install.sh | bash

INSTALL_DIR="${INSTALL_DIR:-/opt/matprat}"
REPO_URL="https://raw.githubusercontent.com/mariugul/matprat-website/main/production"

echo "========================================"
echo "  Matprat Website Production Installer"
echo "========================================"
echo ""

# Create install directory
echo "📁 Creating install directory: $INSTALL_DIR"
sudo mkdir -p "$INSTALL_DIR"
sudo chown "$USER:$USER" "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download docker-compose.yml
echo "📥 Downloading docker-compose.yml..."
curl -fsSL "$REPO_URL/docker-compose.yml" -o docker-compose.yml

# Create .env file if it doesn't exist
if [ ! -f .env ]; then
  echo ""
  echo "🔧 Setting up environment variables..."
  echo "   (Press Enter to use default values)"
  echo ""

  # Database credentials
  read -p "Database password [nodejs]: " DB_PASSWORD
  DB_PASSWORD=${DB_PASSWORD:-nodejs}

  read -p "Database user [nodejs]: " DB_USER
  DB_USER=${DB_USER:-nodejs}

  read -p "Database name [matprat]: " DB_NAME
  DB_NAME=${DB_NAME:-matprat}

  # Postgres admin password
  read -p "Postgres admin password [postgres]: " POSTGRES_PASSWORD
  POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

  # pgAdmin credentials
  read -p "pgAdmin email [admin@localhost]: " PGADMIN_EMAIL
  PGADMIN_EMAIL=${PGADMIN_EMAIL:-admin@localhost}

  read -p "pgAdmin password [admin]: " PGADMIN_PASSWORD
  PGADMIN_PASSWORD=${PGADMIN_PASSWORD:-admin}

  read -p "pgAdmin port [5050]: " PGADMIN_PORT
  PGADMIN_PORT=${PGADMIN_PORT:-5050}

  # Web port
  read -p "Website port [3000]: " WEB_PORT
  WEB_PORT=${WEB_PORT:-3000}

  # Session secret (auto-generate if not provided)
  read -p "Session secret [auto-generate]: " SESSION_SECRET
  if [ -z "$SESSION_SECRET" ]; then
    SESSION_SECRET=$(openssl rand -hex 32)
    echo "   Generated session secret: ${SESSION_SECRET:0:16}..."
  fi

  # Write .env file
  cat > .env <<EOF
# Matprat Production Environment
# Generated by install.sh on $(date)

# Application
SESSION_SECRET=$SESSION_SECRET
WEB_PORT=$WEB_PORT

# Database (Node.js app)
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME

# PostgreSQL
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# pgAdmin
PGADMIN_EMAIL=$PGADMIN_EMAIL
PGADMIN_PASSWORD=$PGADMIN_PASSWORD
PGADMIN_PORT=$PGADMIN_PORT
EOF

  echo "✅ Created .env file"
else
  echo "✅ .env file already exists, skipping configuration"
fi

# Create backup directory
echo "📁 Creating backup directory..."
sudo mkdir -p /var/opt/db_backups
sudo chown "$USER:$USER" /var/opt/db_backups

# Pull and start containers
echo ""
echo "🐳 Pulling Docker images..."
docker compose pull

echo ""
echo "🚀 Starting services..."
docker compose up -d

echo ""
echo "========================================"
echo "  ✅ Installation Complete!"
echo "========================================"
echo ""
echo "Services running:"
echo "  🌐 Website:    http://localhost:${WEB_PORT:-3000}"
echo "  🗄️  pgAdmin:    http://localhost:${PGADMIN_PORT:-5050}"
echo ""
echo "Useful commands:"
echo "  cd $INSTALL_DIR"
echo "  docker compose logs -f      # View logs"
echo "  docker compose restart      # Restart services"
echo "  docker compose down         # Stop services"
echo ""
echo "Watchtower will automatically update containers"
echo "when new images are pushed to Docker Hub."
echo ""
