env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  mocha: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
rules: {}
overrides:
  - files:
      - 'test/**/*.js'
      - 'test/**/*.spec.js'
    rules:
      no-plusplus: off
      no-await-in-loop: off
      global-require: off
