name: Node Continous Integration

on: 
  push:
    branches: [ main ]

jobs:
  install-test-build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: server
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - run: npm run build